# Generated by Django 6.0.5 on 2026-06-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'verbose_name': 'Trajet', 'verbose_name_plural': 'Trajets'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Préférence Utilisateur', 'verbose_name_plural': 'Préférences Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('ride', 'Ride'), ('support', 'Support')], default='ride', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('file', 'File'), ('location', 'Location')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Email, Téléphone ou Nom'),
        ),
    ]
