# Generated by Django 6.0.6 on 2026-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
