# Generated by Django 6.0.5 on 2026-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_app_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbranding',
            name='animation_type',
            field=models.CharField(choices=[('fade_scale', 'Fondu & Zoom'), ('bounce', 'Rebond'), ('pulse', 'Pulsation')], default='fade_scale', max_length=50),
        ),
    ]
