# Generated by Django 6.0.6 on 2026-06-15 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_animation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selfie', models.ImageField(upload_to='verifications/selfies/')),
                ('id_front', models.ImageField(upload_to='verifications/id_fronts/')),
                ('id_back', models.ImageField(upload_to='verifications/id_backs/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de vérification',
                'verbose_name_plural': 'Demandes de vérification',
            },
        ),
    ]
