# Generated by Django 6.0.6 on 2026-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('tricycle', 'Tricycle'), ('voiture', 'Voiture')], default='voiture', max_length=20),
        ),
    ]
