# Generated by Django 6.0.5 on 2026-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mobilesettings_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='FCM Token'),
        ),
    ]
