# Generated by Django 6.0.5 on 2026-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='notes',
            field=models.TextField(blank=True, help_text='Préférences personnalisées du voyageur', null=True),
        ),
    ]
