# Generated by Django 6.0.5 on 2026-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ride_driver_latitude_ride_driver_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='luggage_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='stops_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
