# Generated by Django 6.0.5 on 2026-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userpreference_luggage_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
