# Generated by Django 6.0.5 on 2026-06-19 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ride_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('repeat_type', models.CharField(default='daily', max_length=20)),
                ('week_days', models.JSONField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('departure_location', models.CharField(max_length=255)),
                ('arrival_location', models.CharField(max_length=255)),
                ('price_per_seat', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_series', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Série de Trajets',
                'verbose_name_plural': 'Séries de Trajets',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='api.rideseries'),
        ),
    ]
