# Generated by Django 6.0.5 on 2026-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rideseries_ride_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
