# Generated by Django 6.0.5 on 2026-06-19 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_vehicle_driver_license_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.FloatField(default=10.0)),
                ('min_commission', models.IntegerField(default=100)),
                ('max_commission', models.IntegerField(blank=True, default=2000, null=True)),
                ('is_commission_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Financiers',
                'verbose_name_plural': 'Paramètres Financiers',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('escrow', 'Retenu par Zemy'), ('paid', 'Payé au conducteur'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_payout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='zemy_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='driver_payout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='zemy_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='api.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests_as_driver', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests_as_passenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de Remboursement',
                'verbose_name_plural': 'Demandes de Remboursement',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_payout', models.IntegerField()),
                ('zemy_commission', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Effectué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
