# Generated by Django 6.0.5 on 2026-06-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_financialsettings_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
    ]
