# Generated by Django 6.0.5 on 2026-06-21 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_ride_departure_date_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='accepts_parcels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='allowed_parcel_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_parcels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_weight_per_parcel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='parcels_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='price_per_parcel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='accepts_parcels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='allowed_parcel_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='max_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='max_parcels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='max_weight_per_parcel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rideseries',
            name='price_per_parcel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='parcel_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='parcels_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(max_length=50)),
                ('estimated_value', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parcels/')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('zemy_commission', models.IntegerField(default=0)),
                ('driver_payout', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('picked_up', 'Récupéré'), ('in_transit', 'En cours'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('escrow', 'Retenu par Zemy'), ('paid', 'Payé au conducteur'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='api.ride')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
            },
        ),
    ]
