# Generated by Django 6.0.5 on 2026-06-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ride_accepts_parcels_ride_allowed_parcel_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='is_parcel_commission_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='max_parcel_commission',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='min_parcel_commission',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='parcel_commission_percentage',
            field=models.FloatField(default=8.0),
        ),
    ]
