# Generated by Django 6.0.5 on 2026-06-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_financialsettings_is_parcel_commission_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.parcel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ride', 'Trajet'), ('parcel', 'Colis'), ('withdrawal', 'Retrait'), ('refund', 'Remboursement')], default='ride', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='driver_payout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='zemy_commission',
            field=models.IntegerField(default=0),
        ),
    ]
