# Generated by Django 6.0.5 on 2026-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_archive_reason_user_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
