# Generated by Django 6.0.5 on 2026-06-23 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_verificationrequest_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='rejection_reason',
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_content', models.TextField()),
                ('modified_content', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('modified', 'Modifié'), ('blocked', 'Bloqué')], max_length=20)),
                ('detected_types', models.JSONField(default=list, help_text="Liste des types d'informations personnelles détectées (ex: phone, whatsapp, email)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='api.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Modération',
                'verbose_name_plural': 'Logs de Modération',
                'ordering': ['-created_at'],
            },
        ),
    ]
