# Generated by Django 6.0.5 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_verificationrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
