# Generated by Django 6.0.5 on 2026-06-23 13:15

import uuid
from django.db import migrations, models

def populate_popular_places(apps, schema_editor):
    PopularPlace = apps.get_model('api', 'PopularPlace')
    places = [
        {"name": "Étoile Rouge", "latitude": 6.3686, "longitude": 2.4172, "city": "Cotonou"},
        {"name": "Carrefour IITA", "latitude": 6.4258, "longitude": 2.3387, "city": "Abomey-Calavi"},
        {"name": "Marché Dantokpa", "latitude": 6.3678, "longitude": 2.4348, "city": "Cotonou"},
        {"name": "Université d'Abomey-Calavi (UAC)", "latitude": 6.4174, "longitude": 2.3483, "city": "Abomey-Calavi"},
        {"name": "Aéroport Cardinal Bernardin Gantin", "latitude": 6.3533, "longitude": 2.3854, "city": "Cotonou"},
        {"name": "Carrefour Tankpè", "latitude": 6.4385, "longitude": 2.3551, "city": "Abomey-Calavi"},
        {"name": "Tokan", "latitude": 6.4531, "longitude": 2.3163, "city": "Abomey-Calavi"},
        {"name": "Godomey", "latitude": 6.3797, "longitude": 2.3353, "city": "Abomey-Calavi"},
        {"name": "Fidjrossè", "latitude": 6.3592, "longitude": 2.3684, "city": "Cotonou"},
        {"name": "Akpakpa", "latitude": 6.3725, "longitude": 2.4578, "city": "Cotonou"},
        {"name": "Womey", "latitude": 6.4215, "longitude": 2.3082, "city": "Abomey-Calavi"},
        {"name": "Arconville", "latitude": 6.4468, "longitude": 2.3444, "city": "Abomey-Calavi"},
        {"name": "Carrefour Club des Rois", "latitude": 6.3601, "longitude": 2.3822, "city": "Cotonou"},
        {"name": "Stade de l'Amitié Général Mathieu Kérékou", "latitude": 6.3861, "longitude": 2.3847, "city": "Cotonou"},
        {"name": "Erevan Supermarché", "latitude": 6.3496, "longitude": 2.3995, "city": "Cotonou"},
        {"name": "Carrefour Cadjehoun", "latitude": 6.3558, "longitude": 2.4042, "city": "Cotonou"},
        {"name": "Carrefour Cica Toyota", "latitude": 6.3708, "longitude": 2.3948, "city": "Cotonou"},
        {"name": "Carrefour Vêdoko", "latitude": 6.3789, "longitude": 2.3888, "city": "Cotonou"},
        {"name": "Plaza de la Bourse (Ganhi)", "latitude": 6.3575, "longitude": 2.4289, "city": "Cotonou"},
        {"name": "Carrefour Kpota", "latitude": 6.3494, "longitude": 2.4497, "city": "Porto-Novo"},
        {"name": "Université de Parakou", "latitude": 9.3148, "longitude": 2.6375, "city": "Parakou"},
    ]
    for p in places:
        PopularPlace.objects.get_or_create(
            name=p["name"],
            latitude=p["latitude"],
            longitude=p["longitude"],
            city=p["city"]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_ride_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du lieu')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lieu populaire',
                'verbose_name_plural': 'Lieux populaires',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(populate_popular_places),
    ]
