# Generated by Django 6.0.5 on 2026-06-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='BJ', max_length=5, verbose_name='Code pays (ISO 2 lettres)'),
        ),
    ]
