# Generated by Django 6.0.5 on 2026-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentatives de vérification')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
            ],
            options={
                'verbose_name': 'OTP de réinitialisation',
                'verbose_name_plural': 'OTPs de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
