# Generated by Django 6.0.5 on 2026-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
