# Generated by Django 6.0.5 on 2026-06-26 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_payment_last_verification_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('problem_ride', 'Problème de trajet'), ('problem_parcel', 'Problème de colis'), ('payment', 'Paiement'), ('account', 'Compte'), ('driver', 'Conducteur'), ('suggestion', 'Suggestion'), ('other', 'Autre')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Traité')], default='new', max_length=20)),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Support',
                'verbose_name_plural': 'Tickets de Support',
                'ordering': ['-created_at'],
            },
        ),
    ]
