# Generated by Django 6.0.5 on 2026-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_payment', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('payment_failed', 'Échec de paiement'), ('expired', 'Expirée'), ('completed', 'Terminée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='feexpay', max_length=50),
        ),
    ]
