# Generated by Django 6.0.5 on 2026-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='feexpay', max_length=50),
        ),
    ]