# Generated by Django 6.0.5 on 2026-07-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_booking_status_alter_payment_provider'),
        ('api', '0038_alter_payment_provider'),
    ]

    operations = [
    ]