# Generated by Django 6.0.5 on 2026-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_merge_20260708_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='price_margin_percent',
            field=models.IntegerField(default=20, help_text='% de marge autorisé autour du prix conseillé (min/max)'),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='price_per_km',
            field=models.IntegerField(default=30, help_text='Prix conseillé en FCFA par km'),
        ),
        migrations.AddField(
            model_name='ride',
            name='air_conditioner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='chatty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='luggage_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='stops_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
