# Generated by Django 6.0.5 on 2026-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_ride_preferences_and_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='selfie_id',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/selfie_ids/'),
        ),
    ]
