# Generated by Django 6.0.5 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_verificationrequest_selfie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='stopovers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
