# Generated by Django 6.0.5 on 2026-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_driverpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpayout',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Note de l'admin lors du traitement", null=True),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='amount',
            field=models.IntegerField(help_text='Montant net dû au conducteur en XOF'),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='phone_number',
            field=models.CharField(help_text='Numéro Mobile Money du conducteur', max_length=30),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('paid', 'Versé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
