# Generated by Django 6.0.5 on 2026-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_driverpayout_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
