# Generated by Django 6.0.5 on 2026-07-30 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_booking_arrival_location_booking_departure_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_place_id', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_place_id', models.CharField(blank=True, max_length=150, null=True)),
                ('waypoints_hash', models.CharField(help_text="Hash SHA256 des points d'arrêt intermédiaires ordonnés", max_length=64)),
                ('route_data', models.JSONField(help_text="Données complètes de l'itinéraire retournées par l'API")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Cache d'itinéraire Google",
                'verbose_name_plural': "Cache d'itinéraires Google",
                'indexes': [models.Index(fields=['origin_place_id', 'destination_place_id', 'waypoints_hash'], name='api_directi_origin__127659_idx')],
            },
        ),
        migrations.CreateModel(
            name='RideLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('seats_available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.IntegerField(help_text='Index chronologique du tronçon dans le trajet')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='api.ride')),
            ],
            options={
                'verbose_name': 'Tronçon de trajet',
                'verbose_name_plural': 'Tronçons de trajets',
                'ordering': ['ride', 'order'],
            },
        ),
    ]
