# Generated by Django 6.0.5 on 2026-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_directionscache_rideleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Place ID Google de l'arrivée"),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place ID Google du départ'),
        ),
        migrations.AddField(
            model_name='rideleg',
            name='end_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Place ID Google de l'arrivée du tronçon"),
        ),
        migrations.AddField(
            model_name='rideleg',
            name='start_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place ID Google du départ du tronçon'),
        ),
    ]
