# Generated by Django 6.0.5 on 2026-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_place_ids_to_ride_and_rideleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix personnalisé conducteur'),
        ),
    ]
