# Generated by Django 6.0.5 on 2026-07-31 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_booking_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Accepter automatiquement les demandes de réservation'),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_leg_index',
            field=models.IntegerField(default=0, help_text="Index du tronçon en cours d'exécution"),
        ),
        migrations.AddField(
            model_name='rideleg',
            name='distance_m',
            field=models.IntegerField(default=0, help_text='Distance réelle du tronçon en mètres'),
        ),
        migrations.AddField(
            model_name='rideleg',
            name='duration_sec',
            field=models.IntegerField(default=0, help_text='Durée réelle du tronçon en secondes'),
        ),
        migrations.AddField(
            model_name='rideleg',
            name='leg_status',
            field=models.CharField(choices=[('upcoming', 'À venir'), ('active', 'En cours'), ('completed', 'Terminé')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_location', models.CharField(blank=True, max_length=255)),
                ('arrival_location', models.CharField(blank=True, max_length=255)),
                ('departure_latitude', models.FloatField(blank=True, null=True)),
                ('departure_longitude', models.FloatField(blank=True, null=True)),
                ('arrival_latitude', models.FloatField(blank=True, null=True)),
                ('arrival_longitude', models.FloatField(blank=True, null=True)),
                ('desired_date', models.DateField()),
                ('seats_needed', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de recherche',
                'verbose_name_plural': 'Alertes de recherche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideWaypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Nom de la localité (extrait des steps Google ou reverse géocodé)', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(help_text="Position dans l'itinéraire (index chronologique)")),
                ('distance_from_start_m', models.IntegerField(default=0, help_text='Distance cumulée en mètres depuis le départ du trajet')),
                ('leg_index', models.IntegerField(default=0, help_text='Index du RideLeg auquel appartient ce waypoint')),
                ('is_stopover', models.BooleanField(default=False, help_text="True si c'est un arrêt déclaré par le chauffeur")),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='api.ride')),
            ],
            options={
                'verbose_name': 'Point de passage',
                'verbose_name_plural': 'Points de passage',
                'ordering': ['ride', 'order'],
                'indexes': [models.Index(fields=['ride', 'order'], name='api_rideway_ride_id_c1b120_idx'), models.Index(fields=['latitude', 'longitude'], name='api_rideway_latitud_5a21d2_idx')],
            },
        ),
    ]
