# Generated by Django 6.0.5 on 2026-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_ridewaypoint_searchalert_leg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_waypoint_order',
            field=models.IntegerField(blank=True, help_text='Index du waypoint de descente', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_waypoint_order',
            field=models.IntegerField(blank=True, help_text='Index du waypoint de montée', null=True),
        ),
        migrations.AddField(
            model_name='ridewaypoint',
            name='seats_available',
            field=models.IntegerField(default=4, help_text='Nombre de places disponibles sur le tronçon partant de ce waypoint'),
        ),
    ]
