# Generated by Django 6.0.5 on 2026-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_booking_arrival_latitude_booking_arrival_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_passenger', 'En attente de confirmation passager'), ('pending_payment', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('payment_failed', 'Échec de paiement'), ('expired', 'Expirée'), ('completed', 'Terminée')], default='pending', max_length=20),
        ),
    ]
