# Generated by Django 6.0.5 on 2026-07-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_driver', 'En attente de validation conducteur'), ('pending_passenger', 'En attente de confirmation passager'), ('pending_payment', 'En attente de paiement'), ('payment_processing', 'Paiement en cours'), ('confirmed', 'Confirmée'), ('started', 'Démarrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('expired', 'Expirée'), ('payment_failed', 'Échec de paiement'), ('payment_refunded', 'Remboursée')], default='pending', max_length=20),
        ),
    ]
