# Generated by Django 6.0.5 on 2026-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_counter_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contre-proposition du chauffeur'),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_message',
            field=models.TextField(blank=True, null=True, verbose_name='Message de négociation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_proposed_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix proposé par le passager'),
        ),
    ]
