# Generated by Django 6.0.5 on 2026-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_booking_driver_counter_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridewaypoint',
            name='duration_from_start_sec',
            field=models.IntegerField(default=0, help_text='Durée cumulée en secondes depuis le départ du trajet'),
        ),
        migrations.AddField(
            model_name='ridewaypoint',
            name='waypoint_type',
            field=models.CharField(choices=[('departure', 'Départ'), ('stopover', 'Arrêt'), ('city', 'Ville traversée'), ('gps', 'Point GPS'), ('arrival', 'Arrivée')], default='gps', max_length=50),
        ),
    ]
