# Generated by Django 6.0.5 on 2026-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_ridewaypoint_duration_from_start_sec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionscache',
            options={'verbose_name': "Cache d'itinÃ©raire Google", 'verbose_name_plural': "Cache d'itinÃ©raires Google"},
        ),
        migrations.AlterModelOptions(
            name='financialsettings',
            options={'verbose_name': 'ParamÃ¨tres Financiers', 'verbose_name_plural': 'ParamÃ¨tres Financiers'},
        ),
        migrations.AlterModelOptions(
            name='mobilesettings',
            options={'verbose_name': 'ParamÃ¨tres Mobile', 'verbose_name_plural': 'ParamÃ¨tres Mobile'},
        ),
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de ModÃ©ration', 'verbose_name_plural': 'Logs de ModÃ©ration'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP de rÃ©initialisation', 'verbose_name_plural': 'OTPs de rÃ©initialisation'},
        ),
        migrations.AlterModelOptions(
            name='rideleg',
            options={'ordering': ['ride', 'order'], 'verbose_name': 'TronÃ§on de trajet', 'verbose_name_plural': 'TronÃ§ons de trajets'},
        ),
        migrations.AlterModelOptions(
            name='rideseries',
            options={'verbose_name': 'SÃ©rie de Trajets', 'verbose_name_plural': 'SÃ©ries de Trajets'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'PrÃ©fÃ©rence Utilisateur', 'verbose_name_plural': 'PrÃ©fÃ©rences Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'VÃ©hicule', 'verbose_name_plural': 'VÃ©hicules'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'verbose_name': 'Demande de vÃ©rification', 'verbose_name_plural': 'Demandes de vÃ©rification'},
        ),
        migrations.AlterField(
            model_name='directionscache',
            name='route_data',
            field=models.JSONField(help_text="DonnÃ©es complÃ¨tes de l'itinÃ©raire retournÃ©es par l'API"),
        ),
        migrations.AlterField(
            model_name='directionscache',
            name='waypoints_hash',
            field=models.CharField(help_text="Hash SHA256 des points d'arrÃªt intermÃ©diaires ordonnÃ©s", max_length=64),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='amount',
            field=models.IntegerField(help_text='Montant net dÃ» au conducteur en XOF'),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='phone_number',
            field=models.CharField(help_text='NumÃ©ro Mobile Money du conducteur', max_length=30),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('paid', 'VersÃ©'), ('failed', 'Ã‰chouÃ©')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialsettings',
            name='price_margin_percent',
            field=models.IntegerField(default=20, help_text='% de marge autorisÃ© autour du prix conseillÃ© (min/max)'),
        ),
        migrations.AlterField(
            model_name='financialsettings',
            name='price_per_km',
            field=models.IntegerField(default=30, help_text='Prix conseillÃ© en FCFA par km'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action_taken',
            field=models.CharField(choices=[('modified', 'ModifiÃ©'), ('blocked', 'BloquÃ©')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='detected_types',
            field=models.JSONField(default=list, help_text="Liste des types d'informations personnelles dÃ©tectÃ©es (ex: phone, whatsapp, email)"),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('escrow', 'Retenu par Zemy'), ('paid', 'PayÃ© au conducteur'), ('refunded', 'RemboursÃ©')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'AcceptÃ©'), ('picked_up', 'RÃ©cupÃ©rÃ©'), ('in_transit', 'En cours'), ('delivered', 'LivrÃ©'), ('cancelled', 'AnnulÃ©')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Tentatives de vÃ©rification'),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='VÃ©rifiÃ©'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'ApprouvÃ©e'), ('rejected', 'RejetÃ©e')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Place ID Google de l'arrivÃ©e"),
        ),
        migrations.AlterField(
            model_name='ride',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Accepter automatiquement les demandes de rÃ©servation'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='current_leg_index',
            field=models.IntegerField(default=0, help_text="Index du tronÃ§on en cours d'exÃ©cution"),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place ID Google du dÃ©part'),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='distance_m',
            field=models.IntegerField(default=0, help_text='Distance rÃ©elle du tronÃ§on en mÃ¨tres'),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='duration_sec',
            field=models.IntegerField(default=0, help_text='DurÃ©e rÃ©elle du tronÃ§on en secondes'),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='end_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Place ID Google de l'arrivÃ©e du tronÃ§on"),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='leg_status',
            field=models.CharField(choices=[('upcoming', 'Ã€ venir'), ('active', 'En cours'), ('completed', 'TerminÃ©')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='order',
            field=models.IntegerField(help_text='Index chronologique du tronÃ§on dans le trajet'),
        ),
        migrations.AlterField(
            model_name='rideleg',
            name='start_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place ID Google du dÃ©part du tronÃ§on'),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='distance_from_start_m',
            field=models.IntegerField(default=0, help_text='Distance cumulÃ©e en mÃ¨tres depuis le dÃ©part du trajet'),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='duration_from_start_sec',
            field=models.IntegerField(default=0, help_text='DurÃ©e cumulÃ©e en secondes depuis le dÃ©part du trajet'),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='is_stopover',
            field=models.BooleanField(default=False, help_text="True si c'est un arrÃªt dÃ©clarÃ© par le chauffeur"),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='name',
            field=models.CharField(blank=True, help_text='Nom de la localitÃ© (extrait des steps Google ou reverse gÃ©ocodÃ©)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='order',
            field=models.IntegerField(help_text="Position dans l'itinÃ©raire (index chronologique)"),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='seats_available',
            field=models.IntegerField(default=4, help_text='Nombre de places disponibles sur le tronÃ§on partant de ce waypoint'),
        ),
        migrations.AlterField(
            model_name='ridewaypoint',
            name='waypoint_type',
            field=models.CharField(choices=[('departure', 'DÃ©part'), ('stopover', 'ArrÃªt'), ('city', 'Ville traversÃ©e'), ('gps', 'Point GPS'), ('arrival', 'ArrivÃ©e')], default='gps', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('problem_ride', 'ProblÃ¨me de trajet'), ('problem_parcel', 'ProblÃ¨me de colis'), ('payment', 'Paiement'), ('account', 'Compte'), ('driver', 'Conducteur'), ('suggestion', 'Suggestion'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'TraitÃ©')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'EffectuÃ©')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Email, TÃ©lÃ©phone ou Nom'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='notes',
            field=models.TextField(blank=True, help_text='PrÃ©fÃ©rences personnalisÃ©es du voyageur', null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'ApprouvÃ©e'), ('rejected', 'RejetÃ©e')], default='pending', max_length=20),
        ),
    ]
