# Generated by Django 6.0.5 on 2026-08-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_directionscache_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverpayout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text="Date d'échec du reversement", null=True),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='failure_code',
            field=models.CharField(blank=True, help_text="Code d'erreur FeexPay ou interne", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='failure_reason',
            field=models.TextField(blank=True, help_text="Raison de l'échec du reversement", null=True),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='feexpay_reference',
            field=models.CharField(blank=True, help_text='Référence de la transaction FeexPay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='operator',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('celtiis', 'Celtiis Cash'), ('other', 'Autre')], default='mtn', help_text='Opérateur Mobile Money', max_length=20),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='payment_mode',
            field=models.CharField(choices=[('automatic', 'Automatique (FeexPay)'), ('manual', 'Manuel (Admin)')], default='manual', help_text='Mode de paiement utilisé', max_length=20),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Référence interne Zemy (ZMY-PAYOUT-XXXXXXXX)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Date de passage en processing', null=True),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='amount',
            field=models.IntegerField(help_text='Montant demandé en XOF'),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Date de confirmation du paiement réel', null=True),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='phone_number',
            field=models.CharField(help_text='Numéro Mobile Money du conducteur', max_length=30),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_payouts', to='api.ride'),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('paid', 'Versé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
