# Generated by Django 6.0.5 on 2026-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_driverpayout_enriched'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
