# Generated by Django 6.0.5 on 2026-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_notification_data_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location_extra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'arrivee personnalise"),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_surcharge',
            field=models.IntegerField(default=0, verbose_name='Surcout arrivee personnalise'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location_extra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de depart personnalise'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_surcharge',
            field=models.IntegerField(default=0, verbose_name='Surcout depart personnalise'),
        ),
    ]
