# Generated by Django 6.0.5 on 2026-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_booking_dropoff_location_extra_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'started'])), fields=('driver', 'departure_date', 'departure_time'), name='unique_active_ride_per_driver_datetime'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('seats_available__gte', 0)), name='ride_seats_available_non_negative'),
        ),
    ]
