# Generated by Django on 2026-09-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_audit_ride_db_constraints'),
    ]

    operations = [
    ]
