"""
========================================================

Fichier :
settings.py

Description :

Module de l'application Zemy.

Projet :
Zemy

========================================================
"""
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
def load_dotenv():
    env_file = BASE_DIR / '.env'
    if env_file.exists():
        try:
            with open(env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        k, v = line.split('=', 1)
                        k = k.strip()
                        v = v.strip()
                        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                            v = v[1:-1]
                        os.environ[k] = v
        except Exception as e:
            print(f"Error loading .env file: {e}")

load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY : la SECRET_KEY ne doit JAMAIS avoir de valeur par défaut en production.
_secret_key_env = os.getenv('DJANGO_SECRET_KEY', '')
if not _secret_key_env:
    import sys
    if 'test' not in sys.argv and not os.getenv('DJANGO_DEBUG', 'False') == 'True':
        raise RuntimeError(
            "DJANGO_SECRET_KEY n'est pas définie. "
            "Configurez cette variable d'environnement sur le serveur."
        )
    # En développement/test, on utilise une clé temporaire
    _secret_key_env = 'django-dev-insecure-key-must-not-be-used-in-production'
SECRET_KEY = _secret_key_env

# SECURITY WARNING: don't run with debug turned on in production!
# Par défaut DEBUG=False — nécessite DJANGO_DEBUG=True pour activer en dev.
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# En production, DJANGO_ALLOWED_HOSTS doit être configuré explicitement.
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,zemy.erika-app.com,node239-eu.n0c.com').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server — doit être en premier
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # SEV-008: JWT token blacklist
    'corsheaders',
    'channels',  # Django Channels WebSocket
    'drf_spectacular',
    'api',
]

# Application ASGI (Channels)
ASGI_APPLICATION = 'config.asgi.application'

# Channel Layers — Redis en production (détecté par la variable d'env REDIS_URL), InMemory localement
REDIS_URL = os.getenv('REDIS_URL', '')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
                'capacity': 1500,
                'expiry': 10,
            },
        }
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.PyRedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'zemy-default-cache',
            'TIMEOUT': 300,
        }
    }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'api.middleware.HostOverrideMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')

if DB_NAME and DB_USER:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST or 'localhost',
            'PORT': DB_PORT or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings to prevent FileNotFoundError in temp directories
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'tmp')
if not os.path.exists(FILE_UPLOAD_TEMP_DIR):
    os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Sécurité HTTPS en Production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# SEV-004: CORS restreint en production, ouvert uniquement en développement
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'https://zemy.erika-app.com'
    ).split(',')
    CORS_ALLOW_ALL_ORIGINS = False

# FeexPay Configuration — Paiement entrant (passager)
FEEXPAY_API_TOKEN = os.getenv('FEEXPAY_API_TOKEN', '')
FEEXPAY_MERCHANT_ID = os.getenv('FEEXPAY_MERCHANT_ID', '')
FEEXPAY_MODE = os.getenv('FEEXPAY_MODE', 'SANDBOX')  # 'SANDBOX' ou 'LIVE'
# SEV-002: Secret pour vérifier la signature des webhooks FeexPay
FEEXPAY_WEBHOOK_SECRET = os.getenv('FEEXPAY_WEBHOOK_SECRET', '')

# Alerte de sécurité si SANDBOX actif en démarrage
if FEEXPAY_MODE == 'SANDBOX':
    import logging as _logging
    _logging.getLogger('api').warning(
        "[SECURITE] FEEXPAY_MODE=SANDBOX actif. "
        "Les paiements ne sont PAS réels. Ne pas utiliser en production."
    )

# FeexPay Payout Configuration — Reversement conducteur (Mobile Money sortant)
# Mettre FEEXPAY_PAYOUT_ENABLED=True UNIQUEMENT lorsque l'URL et les credentials Payout
# sont confirmés par FeexPay. En attendant, le mode manuel (admin) reste actif.
FEEXPAY_PAYOUT_ENABLED = os.getenv('FEEXPAY_PAYOUT_ENABLED', 'False').lower() == 'true'
FEEXPAY_PAYOUT_URL = os.getenv('FEEXPAY_PAYOUT_URL', '')           # À configurer avec l'URL FeexPay Payout
FEEXPAY_PAYOUT_STATUS_URL = os.getenv('FEEXPAY_PAYOUT_STATUS_URL', '')  # URL de vérification statut (optionnel)

AUTH_USER_MODEL = 'api.User'

AUTHENTICATION_BACKENDS = [
    'api.backends.EmailOrPhoneModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.backends.SafeJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # SEV-003: Rate limiting global pour protéger contre le brute force et le DoS
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/hour',
        'user': '2000/hour',
        # Throttles custom pour les endpoints sensibles
        'login': '10/minute',
        'otp': '5/minute',
        'reset': '5/hour',
        'payment': '20/minute',
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    # SEV-008: Durée réduite + rotation activée
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),   # 24h (réduit depuis 7j)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,                   # Nouveau token refresh à chaque renouvellement
    'BLACKLIST_AFTER_ROTATION': True,                # Invalider l'ancien refresh token
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'zemy-api',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_BLACKLIST_ENABLED': True,
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Trusted origins for CSRF (Nuxt dashboard)
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001'
).split(',')

JAZZMIN_SETTINGS = {
    "site_title": "Zemy Admin",
    "site_header": "Zemy",
    "site_brand": "Zemy",
    "site_icon": "images/favicon.png",
    "welcome_sign": "Bienvenue sur l'administration",
    "copyright": "Zemy © 2026",
    "search_model": ["api.User", "api.Ride"],
    "user_avatar": "avatar",
    "topmenu_links": [
        {"name": "Tableau de bord", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le site", "url": "/api/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Mon profil", "url": "admin:api_user_change", "icon": "fas fa-user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],
    "hide_models": [],
    "order_with_respect_to": ["api", "api.User", "api.Ride", "api.Booking", "api.Vehicle", "api.Conversation", "api.Message", "api.UserPreference"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "api": "fas fa-database",
        "api.User": "fas fa-user-circle",
        "api.Vehicle": "fas fa-car",
        "api.Ride": "fas fa-route",
        "api.Booking": "fas fa-ticket-alt",
        "api.Conversation": "fas fa-comments",
        "api.Message": "fas fa-comment-dots",
        "api.UserPreference": "fas fa-sliders-h",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-dot-circle",
    "related_modal_active": True,
    "custom_css": "css/custom_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"api.user": "collapsible"},
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Zemy API',
    'DESCRIPTION': 'Documentation officielle de l\'API Zemy.\n\nCette API permet de gérer :\n\n• Authentification\n• Utilisateurs\n• Conducteurs\n• Passagers\n• Trajets\n• Réservations\n• Paiements\n• Colis\n• Vérification des comptes\n• Notifications\n• Messagerie\n• Dashboard Administrateur',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'deepLinking': True,
        'displayOperationId': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'bearerAuth': []}],
    'SECURITY_SCHEMES': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },
    'CONTACT': {
        'name': 'Support Zemy',
        'email': 'support@zemy.app',
    },
    'LICENSE': {
        'name': 'Propriétaire',
    },
    'CAMELIZE_NAMES': False,
    'ENUM_NAME_OVERRIDES': {'StatusEnum': 'api.models.Ride.STATUS_CHOICES'},
    'POSTPROCESSING_HOOKS': [
        'api.swagger_hooks.custom_tag_hook',
        'drf_spectacular.hooks.postprocess_schema_enums'
    ]
}

# Configuration de l'Email et du serveur SMTP (Titan) - Reload Trigger 2
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Zemy <noreply@zemy.app>')

# Si en mode DEBUG et qu'aucun identifiant SMTP n'est renseigné,
# rediriger l'envoi vers la console de développement pour éviter les plantages
if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuration de la journalisation (Logging) pour le projet
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SEV-001: Supprimer la clé hardcodée — la clé doit venir de l'environnement uniquement
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# Configuration de Celery & Redis
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_COMPRESSION = 'gzip'

import sys
if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'

