import { StyleSheet, Dimensions, Platform } from 'react-native';
import { theme } from '../../../../styles/theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  scrollContent: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  profileHeaderCard: {
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.xl,
    paddingBottom: theme.spacing.md,
    marginBottom: theme.spacing.md,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  profileMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.lg,
  },
  avatarWrapperSmall: { position: 'relative' },
  avatarBig: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarBigText: { color: theme.colors.white, fontSize: 28, fontWeight: '800' },
  avatarEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.white,
  },
  profileText: { flex: 1 },
  profileName: { fontSize: 20, fontWeight: '800', color: theme.colors.text, marginBottom: 4 },
  premiumTags: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
    flexWrap: 'wrap'
  },
  ratingBadge: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#FFFBEB',
    paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 8, gap: 4,
  },
  ratingText: { fontSize: 11, fontWeight: '700', color: '#B45309' },
  roleBadge: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: `${theme.colors.primary}15`,
    paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 8, gap: 4,
  },
  roleText: { fontSize: 11, fontWeight: '700', color: theme.colors.primary },
  verifiedBadgePremium: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 8, gap: 4,
  },
  verifiedTextPremium: { fontSize: 11, fontWeight: '700', color: '#047857' },
  unverifiedBadgePremium: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 8, gap: 4,
    borderWidth: 1, borderColor: '#FECACA'
  },
  unverifiedTextPremium: { fontSize: 11, fontWeight: '700', color: '#DC2626' },
  profilePhone: { fontSize: 13, color: theme.colors.textLight },
  statsRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    borderTopWidth: 1, borderTopColor: theme.colors.border, paddingTop: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  statCol: { alignItems: 'center', flex: 1 },
  statNumber: { fontSize: 20, fontWeight: '800', color: theme.colors.text },
  statLabel: { fontSize: 11, color: theme.colors.textLight, fontWeight: '500', marginTop: 2 },
  statDivider: { width: 1, height: 30, backgroundColor: theme.colors.border },
  memberSinceText: {
    textAlign: 'center',
    fontSize: 12,
    color: theme.colors.textMuted,
    fontStyle: 'italic',
  },
  progressContainer: {
    marginBottom: theme.spacing.lg,
    paddingHorizontal: 4,
  },
  progressLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  progressBar: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    marginTop: 6,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 4,
  },
  section: { marginBottom: theme.spacing.lg },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing.sm,
    paddingLeft: 4,
  },
  menuCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.borderRadius.lg,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row', alignItems: 'center',
    padding: theme.spacing.md,
    backgroundColor: theme.colors.white,
  },
  menuIconContainer: {
    width: 40, height: 40, borderRadius: 20,
    justifyContent: 'center', alignItems: 'center',
    marginRight: theme.spacing.md
  },
  menuTextContainer: { flex: 1 },
  menuTitle: { fontSize: 15, fontWeight: '600', color: theme.colors.text },
  menuSubtitle: { fontSize: 12, color: theme.colors.textMuted, marginTop: 2 },
  menuDivider: { height: 1, backgroundColor: theme.colors.border, marginHorizontal: theme.spacing.md },
  logoutBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 8, backgroundColor: theme.colors.errorLight, height: 52,
    borderRadius: theme.borderRadius.lg, marginTop: theme.spacing.sm,
  },
  logoutBtnText: { fontSize: 15, fontWeight: '700', color: theme.colors.error },
  versionText: {
    textAlign: 'center',
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: theme.spacing.xl,
  },
  loginButton: {
    borderRadius: theme.borderRadius.lg,
    overflow: 'hidden',
  },
  loginButtonGradient: {
    paddingHorizontal: 32,
    paddingVertical: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginButtonText: {
    color: theme.colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: theme.spacing.xl,
    paddingBottom: 40,
    minHeight: '75%',
    maxHeight: '95%',
  },
  modalDragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.text,
  },
  modernAvatarPicker: {
    alignSelf: 'center',
    marginBottom: theme.spacing.xl,
  },
  avatarWrapper: {
    position: 'relative',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  modernAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: theme.colors.white,
  },
  modernAvatarEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.primary,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.white,
  },
  modernAvatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernAvatarText: {
    fontSize: 11,
    color: theme.colors.white,
    fontWeight: '600',
    marginTop: 4,
  },
  vehicleIconContainer: {
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  vehicleTypeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 8,
    marginLeft: 4,
  },
  vehicleTypeContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: theme.spacing.lg,
  },
  vehicleTypeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  vehicleTypeBtnActive: {
    backgroundColor: `${theme.colors.primary}15`,
    borderColor: theme.colors.primary,
  },
  vehicleTypeText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textMuted,
  },
  vehicleTypeTextActive: {
    color: theme.colors.primary,
  },
  vehicleIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F8FA',
    borderRadius: 16,
    height: 56,
    paddingHorizontal: 16,
    marginBottom: theme.spacing.md,
  },
  inputIcon: {
    marginRight: 12,
  },
  modalInputModern: {
    flex: 1,
    fontSize: 15,
    color: theme.colors.text,
    height: '100%',
  },
  modalBtnGradient: {
    flexDirection: 'row',
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: theme.spacing.sm,
    gap: 8,
  },
  modalBtnSaveText: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.white,
  },
  errorText: {
    color: theme.colors.error,
    fontSize: 12,
    marginBottom: theme.spacing.md,
    marginTop: -8,
    marginLeft: 4,
  },
  // Preferences Cards
  prefCardsContainer: {
    gap: 12,
  },
  prefRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F8FA',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  prefIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  prefRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: theme.colors.textMuted,
  },
  // OTP and Password modal styles
  otpContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
  },
  otpBox: {
    width: 44,
    height: 48,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
  },
  otpBoxFocused: {
    borderColor: theme.colors.primary,
    backgroundColor: '#fff',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  otpBoxFilled: {
    borderColor: theme.colors.primary,
  },
  otpText: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text,
  },
  hiddenInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  resendContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  resendText: {
    fontSize: 13,
    color: theme.colors.textLight,
  },
  timerText: {
    fontWeight: '600',
    color: theme.colors.primary,
  },
  resendLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.primary,
    textDecorationLine: 'underline',
  },
  successWrapper: {
    alignItems: 'center',
    paddingTop: 20,
  },
  successIconWrapper: {
    marginBottom: 16,
    shadowColor: theme.colors.success || '#10B981',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  stepWrapper: {
    width: '100%',
    paddingTop: 10,
  },
  modalSubtitle: {
    fontSize: 14,
    color: theme.colors.textMuted,
    lineHeight: 22,
    marginBottom: 20,
  },
  modalHighlightText: {
    fontWeight: '600',
    color: theme.colors.text,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  modalButton: {
    height: 56,
    borderRadius: 16,
    overflow: 'hidden',
    marginTop: 10,
  },
  disabledButton: {
    opacity: 0.7,
  },
  modalStepContainer: {
    width: '100%',
  },
});
